CredCab/config/routes.rb
CredCab::Application.routes.draw do

  get "admins/index", to: 'admins#index'
  get "admins/show"
  get "admins/edit"
  get "admins/update"

  devise_for :admins
  devise_for :users
  root 'home#index'

  resources :credentials
  resources :courses
  resources :hours

  delete '/credentials/:id(.:format)', to: 'credentials#destroy'

  get '/about',   to: 'static_pages#about'  
  get '/privacy', to: 'static_pages#privacy'

end

CredCab/app/models/credential.rb
class Credential < ActiveRecord::Base

	validates :title, :issuing_authority, :date_issued, :last_renewal, :next_renewal, :hoursrequired, presence: true
	validates :title, length: { minimum: 5, maximum: 50 }
	validates :hoursrequired, :numericality => {:greater_than_or_equal_to => 1 }
	# validates :credential_image, format: { with: /\A\w+.pdf\z/ }


	belongs_to :user
  	has_many :labels
  	has_many :courses, :through => :labels

  	mount_uploader :credential_image, CredimageUploader



end

CredCab/app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController


	def index
		# @credentials = Credential.all
		@credentials = current_user.credentials
	end

	def new
		# @credentials = Credential.new
		@credentials = current_user.credentials.new
	end

	def create
		safe_params = params.require('credential').permit(:title, :issuing_authority, :date_issued, :last_renewal, :next_renewal, :hoursrequired, :credential_image)
  	 	@credentials = current_user.credentials.new(safe_params)	
  	 	# @credential = Credential.new(safe_params)
	      if @credentials.save
	  	     redirect_to @credentials
	       else
	        render 'new'
	      end
	end

	def show
		@credential = Credential.find(params[:id])
	end

	def edit
		@credentials = Credential.find(params[:id])
	end

	def update
		@credentials = Credential.find(params[:id])
		@credentials.update(cred_params)
		redirect_to @credentials
	end

	def destroy
		Credential.find(params[:id]).destroy
		flash[:success] = "Credential deleted"
		redirect_to credentials_path
	end

		private
		def cred_params
       		params.require('credential').permit(:title, :issuing_authority, :date_issued, :last_renewal, :next_renewal, :hoursrequired, :credential_image)
  		end

end

CredCab/app/helpers/credentials_helper.rb
module CredentialsHelper
end

CredCab/app/views/credentials/edit.html.erb
<h1>Edit Credential</h1>

<% if @credentials.errors.any? %>
	<h2>There were errors updating your credential!</h2>
	<ul>
		  <% @credentials.errors.full_messages.each do |msg| %>
		  <li><%= msg %></li>
		  <% end %>
	</ul>
<% end %>

<section>
		<%= form_for @credentials do |f| %>
			    <p><%= f.text_field :title, :placeholder => "Title" %></p>
			    <p><%= f.text_field :issuing_authority, :placeholder => "Issuing Authority" %></p>
			    <%= f.label :date_issued %>
			    <p><%= f.date_select :date_issued %></p>
			    <%= f.label :last_renewal %>
				<p><%= f.date_select :last_renewal%></p>
				<%= f.label :next_renewal %>
				<p><%= f.date_select :next_renewal%></p>
				<p><%= f.text_field :hoursrequired, :placeholder => "Hours Required for Renewal" %></p>
				
				<%= f.label :Add_Credential_Certificate %>
				<p><%= f.file_field :credential_image %></p>
				<p><label><%= f.check_box :remove_credential_image %> Remove Credential Image</label></p>
				
				<%= f.submit %>
			<% end %>
</section>
</br>

<%= link_to "Cancel", credentials_path %>

CredCab/app/views/credentials/index.html.erb
<h1>My Credentials</h1>

<!--Table to show credentials -->
	<section>
		<table class = "table table-striped">
  			<tr>
			    <th>Title</th>
			    <th>Issuing Authority</th>
			    <th>Date Issued</th>
			    <th>Last Renewal</th>
			    <th>Next Renewal</th>
			    <th>Hours Required </br>for Renewal</th>
			    <th>Image Uploaded</th>
  			</tr>
  			<% @credentials.each do |credential| %>
  			<tr>
			    <td><p><%= credential.title %></p></td>
			    <td><p><%= credential.issuing_authority %></p></td>
			    <td><p><%= credential.date_issued.strftime('%D') %></p></td>
				<td><p><%= credential.last_renewal.strftime('%D') %></p></td>
				<td><p><%= credential.next_renewal.strftime('%D') %></p></td>
				<td><p><%= credential.hoursrequired %></p></td>
				<td><p><%= image_boolean(credential.credential_image) %></p></td>
				<td><p><%= link_to "View", credential %></p></td>
  			</tr>
  			<% end %>
		</table>
	</section>


<%= link_to "Add New Credential", new_credential_path %> | <%= link_to "View Courses", courses_path %>

CredCab/app/views/credentials/new.html.erb
<h1>Add a New Credential</h1>

<div style="color:red;">
<% if @credentials.errors.any? %>
	<h2 >There were errors saving your credential!</h2>
	<ol>
		  <% @credentials.errors.full_messages.each do |msg| %>
		  <li><%= msg %></li>
		  <% end %>
	</ol>
<% end %>

</div>

<section>
  			<%= form_for @credentials do |f| %>
			    <p><%= f.text_field :title, :placeholder => "Title" %></p>
			    <p><%= f.text_field :issuing_authority, :placeholder => "Issuing Authority" %></p>
			    <%= f.label :date_issued %>
			    <p><%= f.date_select :date_issued %></p>
			    <%= f.label :last_renewal %>
				<p><%= f.date_select :last_renewal%></p>
				<%= f.label :next_renewal %>
				<p><%= f.date_select :next_renewal%></p>
				<p><%= f.text_field :hoursrequired, :placeholder => "Hours Required for Renewal" %></p>
				<%= f.label :Add_Credential_Certificate %>
				<p><%= f.file_field :credential_image %></p>
				<%= f.submit %>
			<% end %>
</section>
</br>
<button class="btn" type="submit"><%= link_to "Cancel", credentials_path %></button>

<% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

CredCab/app/views/credentials/show.html.erb
<!--Table to show selected credential -->
	<section>
		<table class = "table table-striped">
  			<tr>
			    <th>Title</th>
			    <th>Issuing Authority</th>
			    <th>Date Issued</th>
			    <th>Last Renewal</th>
			    <th>Next Renewal</th>
			    <th>Hours Required</th>
  			</tr>
  			
  			<tr>
			    <td><p><%= @credential.title %></p></td>
			    <td><p><%= @credential.issuing_authority %></p></td>
			    <td><p><%= @credential.date_issued.strftime('%D') %></p></td>
				<td><p><%= @credential.last_renewal.strftime('%D')%></p></td>
				<td><p><%= @credential.next_renewal.strftime('%D') %></p></td>
				<td><p><%= @credential.hoursrequired %></p></td>
  			</tr>
  			
		</table>
	</section>

<div class="image">
<%= image_tag(@credential.credential_image_url(:thumb).to_s) if @credential.credential_image? %>
</div>

</br>
</br>


<%= link_to "Edit", edit_credential_path(@credential) %> |
<%= link_to "Delete", credential_path(credential_id: @credential.id), method: :delete %>
</br>
</br>
<%= link_to "Return to My Credentials", credentials_path %>