CredCab/config/routes.rb
CredCab::Application.routes.draw do

  get "admins/index", to: 'admins#index'
  get "admins/show"
  get "admins/edit"
  get "admins/update"

  devise_for :admins
  devise_for :users
  root 'home#index'

  resources :credentials
  resources :courses
  resources :hours

  delete '/credentials/:id(.:format)', to: 'credentials#destroy'

  get '/about',   to: 'static_pages#about'  
  get '/privacy', to: 'static_pages#privacy'

end

CredCab/app/controllers/hours_controller.rb
class HoursController < ApplicationController

	def index
		@credentials = current_user.credentials
		@courses = current_user.courses
		# @hours = current_user.credentials.where(credential_id = ).sum 
	end

	def show 
	end 

	def edit
	end

	def create
	end 

	def update
	end 

end

CredCab/app/helpers/hours_helper.rb
module HoursHelper
end

CredCab/app/views/hours/index.html.erb
<h1>My Total Hours</h1>

<!--Table to show hours-->
	<section>
		<table class = "table table-striped">
  			<tr>
			    <th>Title</th>
			    <th>Hours Required</th>
			    <th>Hours Completed</th>
  			</tr>
  			<% @credentials.each do |credential| %>
  			<tr>

			    <td><p><%= credential.title %></p></td>
			    <td><p><%= credential.hoursrequired %></p></td>
			    <td>
					<% @courses.each do |course| %>
					<p><%= course.credits %></p>
					<% end %>
				</td>
			<% end %>
				
  			</tr>
  			
		</table>
	</section>


<%= link_to "View Courses", courses_path %> | <%= link_to "View Credentials", credentials_path %>


			  