WaterStatus_app/config/routes.rb
WaterStatusApp::Application.routes.draw do
  devise_for :users
    root 'static_pages#index'

  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'
  get '/well',  to: 'static_pages#well'  
  get '/search', to: 'static_pages#search'

 

 

end

WaterStatus_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
  	end

  	def create
     user = User.find_by_email(params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
    	sign_in user
    	redirect_back_or user
  	else
      flash.now[:error] = 'Invalid email/password combination.'
      render 'new'
  		end
  	end

  	def destroy
    	sign_out
    	redirect_to root_url
  	end

end

WaterStatus_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end
	
	def about
  	end

  	def contact
  	end

  	def privacy
  	end

	def well
  	end

  	def search
  	end
  	
end

WaterStatus_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.paginate(page:params[:page])
  end

  def new
  	 @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        # sign_in @user
    	  flash[:success] = "Welcome to WaterStatus!"
        redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :zipcode, :password,
                                   :password_confirmation)
    end

    # def signed_in_user
    #   unless signed_in? 
    #   store location
    #   redirect_to signin_url, notice: "Please sign in." unless signed_in?
    # end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

WaterStatus_app/app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title)                          # Method definition
    base_title = "WaterStatus"  					  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{base_title} | #{page_title}"                 # String interpolation
    end
  end
end

WaterStatus_app/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	cookies.permanent[:remember_token] = user.remember_token
    	self.current_user = user
  	end

  	def signed_in?
    	!current_user.nil?
  	end

    def current_user=(user)
    	@current_user = user
  	end

  	def current_user
    	@current_user ||= User.find_by(remember_token: cookies[:remember_token])
  	end
end

WaterStatus_app/app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

WaterStatus_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright 2013. All rights reserved.  
  </small>
  <nav class = "pull-right">
    <ul>
      <li><%= link_to "Home |",    root_path %></li>
      <li><%= link_to "About |",   about_path %></li>
      <li><%= link_to "Privacy |", privacy_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

WaterStatus_app/app/views/layouts/_header.html.erb
<h1><%=link_to "WaterStatus", root_path %></h1>

<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>
<%= link_to "Well", well_path %>
<%= render "layouts/search" %>

WaterStatus_app/app/views/layouts/_search.html.erb
<%= form_tag "/search", method: "GET" do %>
	<%= label_tag :q, "Search"%>
	<%= text_field_tag :q %>
	<%= submit_tag "Search" %>
<% end %>

WaterStatus_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!--  <title><%= content_for?(:title) ? yield(:title) : "WaterStatus" %></title> -->
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">WaterStatus</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <li><%= link_to "About", "/about"  %></li>
              <li><%= link_to "Well", "/well"  %></li>

              <!--If signed in, header links change-->
          
            <% if user_signed_in? %>
              
              <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  My Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", "#" %></li>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
        
            <% if user_signed_in? != true %>
              <li><%= link_to "Join", new_user_registration_path %></li> 
            <% end %>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>

          <% if alert %>
              <p class ="alert"><%= alert %></p>
          <%end%>

          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <%= render 'layouts/footer' %>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

WaterStatus_app/app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h2>At WaterStatus we're connecting water customers and water utilities.</h2>

<p>WaterStatus was founded in 2013 to provide a platform for communication and collaboration among water customers and water utilities. Tell us your suggestions for features you would like to see on the site.</p>

<h1>Frequently Asked Questions</h1>

<h3>Is WaterStatus free?</h3>
<p>Yes. Joining WaterStatus is free for both water customers and water utilities. For water utilities there are premium features that we charge a subscription fee.</p>

<h3>Why should I join WaterStatus?</h3>
<p>Everyone should join WaterStatus to share their water quality and have a voice about their water. You can find out what others in your service think of their water quality. You can rate water quality in the places your travel, and check on water quality before your travel to new places, or if you're thinking of moving to a new location.</p>

<h3>What can I do on the WaterStatus website?</h3>
<p>At WaterStatus you can learn more about water issues, update your WaterStatus, communicate with your water utility, and find out about water quality and issues in the places you are traveling or thinking of moving to.</p>


<h3>Is WaterStatus available worldwide?</h3>
<p>Yes. We are building a water community from around the world.</p>

<h3>What premium features are available to water utilities?</h3>
<p>Premium features include uploading and editing your consumer confidence report, communicating directly with water customers who are members of WaterStatus, generating specific feedback surveys for your customers, reading WaterStatus survey results.</p>

<h3>How much is the subscription fee for water utilities to access premium features?</h3>
<p>Water utilities is free to join, but to access premium features the subscription fee is $200 per treatment plant per year. This supports the site and 10% of subscription fees will go to water research projects.</p>

WaterStatus_app/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h2>WaterStatus is based in New York City.</h2>

<h2>You can reach us at contact@waterstat.us.</h2>

WaterStatus_app/app/views/static_pages/index.html.erb
<% provide(:title, 'Your Water Community') %>

<h2>WaterStatus is your water community.</h2> 

<p>Share your WaterStatus</p>
<p>Navigate water issues</p>
<p>Connect with your water utility and community</p>

WaterStatus_app/app/views/static_pages/privacy.html.erb
<% provide(:title, 'Privacy') %>

<h4>Water quality is public information. Your person information is not.</h4>

WaterStatus_app/app/views/static_pages/well.html.erb
<% provide(:title, 'Water Knowledge') %>

<h1>Water Quality</h1>

<h1>Water Issues</h1>